# Generated by Django 4.1.7 on 2023-02-19 18:50

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_campus_classe_comprovante_estado_status_validacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovante',
            name='arquivo',
            field=models.FileField(upload_to=cadastros.models.user_path),
        ),
    ]
